-- Script de criação das tabelas no Oracle (RM562254) para o CP4

-- 1. Tabela TB_CP4_FILMES
BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE "TB_CP4_FILMES" (
       "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
       "Titulo" NVARCHAR2(100) NOT NULL,
       "Genero" NVARCHAR2(50) NOT NULL,
       "AnoLancamento" NUMBER(10) NOT NULL,
       "NotaImdb" NUMBER(3,1) NOT NULL,
       "DataCadastro" TIMESTAMP(7) NOT NULL,
       CONSTRAINT "PK_TB_CP4_FILMES" PRIMARY KEY ("Id")
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/

-- 2. Tabela TB_CP4_AVALIACOES
BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE "TB_CP4_AVALIACOES" (
       "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
       "Usuario" NVARCHAR2(80) NOT NULL,
       "Comentario" NVARCHAR2(500) NOT NULL,
       "Nota" NUMBER(10) NOT NULL,
       "DataAvaliacao" TIMESTAMP(7) NOT NULL,
       "FilmeId" NUMBER(10) NOT NULL,
       CONSTRAINT "PK_TB_CP4_AVALIACOES" PRIMARY KEY ("Id"),
       CONSTRAINT "FK_TB_CP4_AVALIACOES_TB_CP4_FILMES_FilmeId" 
           FOREIGN KEY ("FilmeId") REFERENCES "TB_CP4_FILMES" ("Id") ON DELETE CASCADE
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
/

-- 3. Índices de Otimização (Critério Obrigatório CP4)
BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX "IX_FILME_TITULO" ON "TB_CP4_FILMES" ("Titulo")';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN NULL; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX "IX_FILME_GENERO" ON "TB_CP4_FILMES" ("Genero")';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN NULL; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX "IX_AVALIACAO_FILMEID" ON "TB_CP4_AVALIACOES" ("FilmeId")';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN NULL; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX "IX_AVALIACAO_USUARIO" ON "TB_CP4_AVALIACOES" ("Usuario")';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN NULL; END IF;
END;
/

-- 4. Inserção dos dados iniciais (Seed)
INSERT INTO "TB_CP4_FILMES" ("Id", "Titulo", "Genero", "AnoLancamento", "NotaImdb", "DataCadastro")
VALUES (1, 'Interestelar', 'Ficção Científica', 2014, 8.7, SYSTIMESTAMP);

INSERT INTO "TB_CP4_FILMES" ("Id", "Titulo", "Genero", "AnoLancamento", "NotaImdb", "DataCadastro")
VALUES (2, 'O Poderoso Chefão', 'Drama', 1972, 9.2, SYSTIMESTAMP);

INSERT INTO "TB_CP4_FILMES" ("Id", "Titulo", "Genero", "AnoLancamento", "NotaImdb", "DataCadastro")
VALUES (3, 'Batman: O Cavaleiro das Trevas', 'Ação', 2008, 9.0, SYSTIMESTAMP);

INSERT INTO "TB_CP4_AVALIACOES" ("Id", "Usuario", "Comentario", "Nota", "DataAvaliacao", "FilmeId")
VALUES (1, 'Thomas', 'Obra-prima do cinema de ficção científica!', 5, SYSTIMESTAMP, 1);

INSERT INTO "TB_CP4_AVALIACOES" ("Id", "Usuario", "Comentario", "Nota", "DataAvaliacao", "FilmeId")
VALUES (2, 'Mariana', 'Trilha sonora e efeitos visuais espetaculares.', 5, SYSTIMESTAMP, 1);

INSERT INTO "TB_CP4_AVALIACOES" ("Id", "Usuario", "Comentario", "Nota", "DataAvaliacao", "FilmeId")
VALUES (3, 'Carlos', 'Um dos maiores clássicos da história do cinema.', 5, SYSTIMESTAMP, 2);

INSERT INTO "TB_CP4_AVALIACOES" ("Id", "Usuario", "Comentario", "Nota", "DataAvaliacao", "FilmeId")
VALUES (4, 'Lucas', 'Atuação lendária do Heath Ledger como Coringa.', 5, SYSTIMESTAMP, 3);

COMMIT;
