using CP4.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CP4.Infrastructure.Data
{
    public static class DbInitializer
    {
        public static void Initialize(AppDbContext context, ILogger logger)
        {
            try
            {
                logger.LogInformation("Inicializando banco de dados...");

                if (context.Database.IsRelational())
                {
                    CriarTabelasOracle(context, logger);
                }
                else
                {
                    context.Database.EnsureCreated();
                }

                PopularDados(context, logger);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Erro na inicialização do banco: {Message}", ex.Message);
            }
        }

        private static void CriarTabelasOracle(AppDbContext context, ILogger logger)
        {
            try
            {
                logger.LogInformation("Garantindo existência das tabelas no Oracle...");

                // 1. Tabela TB_CP4_FILMES
                context.Database.ExecuteSqlRaw(@"
                    BEGIN
                       EXECUTE IMMEDIATE 'CREATE TABLE ""TB_CP4_FILMES"" (
                           ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                           ""Titulo"" NVARCHAR2(100) NOT NULL,
                           ""Genero"" NVARCHAR2(50) NOT NULL,
                           ""AnoLancamento"" NUMBER(10) NOT NULL,
                           ""NotaImdb"" NUMBER(3,1) NOT NULL,
                           ""DataCadastro"" TIMESTAMP(7) NOT NULL,
                           CONSTRAINT ""PK_TB_CP4_FILMES"" PRIMARY KEY (""Id"")
                       )';
                    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                ");

                // 2. Tabela TB_CP4_AVALIACOES
                context.Database.ExecuteSqlRaw(@"
                    BEGIN
                       EXECUTE IMMEDIATE 'CREATE TABLE ""TB_CP4_AVALIACOES"" (
                           ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                           ""Usuario"" NVARCHAR2(80) NOT NULL,
                           ""Comentario"" NVARCHAR2(500) NOT NULL,
                           ""Nota"" NUMBER(10) NOT NULL,
                           ""DataAvaliacao"" TIMESTAMP(7) NOT NULL,
                           ""FilmeId"" NUMBER(10) NOT NULL,
                           CONSTRAINT ""PK_TB_CP4_AVALIACOES"" PRIMARY KEY (""Id""),
                           CONSTRAINT ""FK_AVALIACOES_FILMES"" FOREIGN KEY (""FilmeId"") REFERENCES ""TB_CP4_FILMES"" (""Id"") ON DELETE CASCADE
                       )';
                    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
                    END;
                ");

                // 3. Índices de Otimização
                context.Database.ExecuteSqlRaw(@"
                    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ""IX_FILME_TITULO"" ON ""TB_CP4_FILMES"" (""Titulo"")'; EXCEPTION WHEN OTHERS THEN NULL; END;
                ");
                context.Database.ExecuteSqlRaw(@"
                    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ""IX_FILME_GENERO"" ON ""TB_CP4_FILMES"" (""Genero"")'; EXCEPTION WHEN OTHERS THEN NULL; END;
                ");
                context.Database.ExecuteSqlRaw(@"
                    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ""IX_AVALIACAO_FILMEID"" ON ""TB_CP4_AVALIACOES"" (""FilmeId"")'; EXCEPTION WHEN OTHERS THEN NULL; END;
                ");
                context.Database.ExecuteSqlRaw(@"
                    BEGIN EXECUTE IMMEDIATE 'CREATE INDEX ""IX_AVALIACAO_USUARIO"" ON ""TB_CP4_AVALIACOES"" (""Usuario"")'; EXCEPTION WHEN OTHERS THEN NULL; END;
                ");

                logger.LogInformation("Tabelas e índices no Oracle verificados com sucesso.");
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Tentativa de criar tabelas via DDL automática retornou: {Message}", ex.Message);
            }
        }

        private static void PopularDados(AppDbContext context, ILogger logger)
        {
            try
            {
                if (context.Filmes.Count() == 0)
                {
                    logger.LogInformation("Populando dados iniciais de demonstração (Seed Data)...");

                    var filme1 = new Filme("Interestelar", "Ficção Científica", 2014, 8.7m);
                    var filme2 = new Filme("O Poderoso Chefão", "Drama", 1972, 9.2m);
                    var filme3 = new Filme("Batman: O Cavaleiro das Trevas", "Ação", 2008, 9.0m);

                    context.Filmes.AddRange(filme1, filme2, filme3);
                    context.SaveChanges();

                    var avaliacoes = new List<Avaliacao>
                    {
                        new Avaliacao("Thomas", "Obra-prima do cinema de ficção científica!", 5, filme1.Id),
                        new Avaliacao("Mariana", "Trilha sonora e efeitos visuais espetaculares.", 5, filme1.Id),
                        new Avaliacao("Carlos", "Um dos maiores clássicos da história do cinema.", 5, filme2.Id),
                        new Avaliacao("Lucas", "Atuação lendária do Heath Ledger como Coringa.", 5, filme3.Id)
                    };

                    context.Avaliacoes.AddRange(avaliacoes);
                    context.SaveChanges();

                    logger.LogInformation("Dados iniciais inseridos com sucesso!");
                }
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Não foi possível inserir seed data automaticamente: {Message}", ex.Message);
            }
        }
    }
}
